// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config.proto

/*
Package nebletpb is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Config
	P2PConfig
	RPCConfig
	PowConfig
	DPoSConfig
	StorageConfig
	AccountConfig
	Influxdb
	Metrics
*/
package nebletpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Neblet global configurations.
type Config struct {
	// P2P network config.
	P2P *P2PConfig `protobuf:"bytes,1,opt,name=p2p" json:"p2p,omitempty"`
	// RPC server config.
	Rpc *RPCConfig `protobuf:"bytes,2,opt,name=rpc" json:"rpc,omitempty"`
	// Pow config
	Pow *PowConfig `protobuf:"bytes,3,opt,name=pow" json:"pow,omitempty"`
	// DPoS config
	Dpos *DPoSConfig `protobuf:"bytes,4,opt,name=dpos" json:"dpos,omitempty"`
	// Storage config
	Storage *StorageConfig `protobuf:"bytes,5,opt,name=storage" json:"storage,omitempty"`
	// Account manager config
	Account *AccountConfig `protobuf:"bytes,6,opt,name=account" json:"account,omitempty"`
	// Influxdb config
	Influxdb *Influxdb `protobuf:"bytes,7,opt,name=influxdb" json:"influxdb,omitempty"`
	// Metrics config
	Metrics *Metrics `protobuf:"bytes,8,opt,name=metrics" json:"metrics,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{0} }

func (m *Config) GetP2P() *P2PConfig {
	if m != nil {
		return m.P2P
	}
	return nil
}

func (m *Config) GetRpc() *RPCConfig {
	if m != nil {
		return m.Rpc
	}
	return nil
}

func (m *Config) GetPow() *PowConfig {
	if m != nil {
		return m.Pow
	}
	return nil
}

func (m *Config) GetDpos() *DPoSConfig {
	if m != nil {
		return m.Dpos
	}
	return nil
}

func (m *Config) GetStorage() *StorageConfig {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *Config) GetAccount() *AccountConfig {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Config) GetInfluxdb() *Influxdb {
	if m != nil {
		return m.Influxdb
	}
	return nil
}

func (m *Config) GetMetrics() *Metrics {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type P2PConfig struct {
	// P2P seed node addresses.
	Seed string `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	// P2P node port number.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// P2P node chainID.
	ChainId uint32 `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// P2P node version.
	Version uint32 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *P2PConfig) Reset()                    { *m = P2PConfig{} }
func (m *P2PConfig) String() string            { return proto.CompactTextString(m) }
func (*P2PConfig) ProtoMessage()               {}
func (*P2PConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{1} }

func (m *P2PConfig) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

func (m *P2PConfig) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *P2PConfig) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *P2PConfig) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type RPCConfig struct {
	// API RPC server listening port number.
	ApiPort uint32 `protobuf:"varint,1,opt,name=api_port,json=apiPort,proto3" json:"api_port,omitempty"`
	// Management RPC server listening port number.
	ManagementPort uint32 `protobuf:"varint,2,opt,name=management_port,json=managementPort,proto3" json:"management_port,omitempty"`
	// Json RPC Gateway server listening port number.
	ApiHttpPort uint32 `protobuf:"varint,3,opt,name=api_http_port,json=apiHttpPort,proto3" json:"api_http_port,omitempty"`
	// Management http server listening port number.
	ManagementHttpPort uint32 `protobuf:"varint,4,opt,name=management_http_port,json=managementHttpPort,proto3" json:"management_http_port,omitempty"`
}

func (m *RPCConfig) Reset()                    { *m = RPCConfig{} }
func (m *RPCConfig) String() string            { return proto.CompactTextString(m) }
func (*RPCConfig) ProtoMessage()               {}
func (*RPCConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{2} }

func (m *RPCConfig) GetApiPort() uint32 {
	if m != nil {
		return m.ApiPort
	}
	return 0
}

func (m *RPCConfig) GetManagementPort() uint32 {
	if m != nil {
		return m.ManagementPort
	}
	return 0
}

func (m *RPCConfig) GetApiHttpPort() uint32 {
	if m != nil {
		return m.ApiHttpPort
	}
	return 0
}

func (m *RPCConfig) GetManagementHttpPort() uint32 {
	if m != nil {
		return m.ManagementHttpPort
	}
	return 0
}

type PowConfig struct {
	// pow miner's coinbase
	Coinbase string `protobuf:"bytes,1,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
}

func (m *PowConfig) Reset()                    { *m = PowConfig{} }
func (m *PowConfig) String() string            { return proto.CompactTextString(m) }
func (*PowConfig) ProtoMessage()               {}
func (*PowConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{3} }

func (m *PowConfig) GetCoinbase() string {
	if m != nil {
		return m.Coinbase
	}
	return ""
}

type DPoSConfig struct {
	// dpos miner's coinbase
	Coinbase string `protobuf:"bytes,1,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
}

func (m *DPoSConfig) Reset()                    { *m = DPoSConfig{} }
func (m *DPoSConfig) String() string            { return proto.CompactTextString(m) }
func (*DPoSConfig) ProtoMessage()               {}
func (*DPoSConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{4} }

func (m *DPoSConfig) GetCoinbase() string {
	if m != nil {
		return m.Coinbase
	}
	return ""
}

type StorageConfig struct {
	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (m *StorageConfig) Reset()                    { *m = StorageConfig{} }
func (m *StorageConfig) String() string            { return proto.CompactTextString(m) }
func (*StorageConfig) ProtoMessage()               {}
func (*StorageConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{5} }

func (m *StorageConfig) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type AccountConfig struct {
	// Account transaction sign algorithm type
	Signature uint32 `protobuf:"varint,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Account addr encrypt algorithm type
	Encrypt uint32 `protobuf:"varint,2,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	// Account key file directory
	KeyDir string `protobuf:"bytes,3,opt,name=key_dir,json=keyDir,proto3" json:"key_dir,omitempty"`
	// Account test keyfile's passphrase
	TestPassphrase string `protobuf:"bytes,4,opt,name=test_passphrase,json=testPassphrase,proto3" json:"test_passphrase,omitempty"`
}

func (m *AccountConfig) Reset()                    { *m = AccountConfig{} }
func (m *AccountConfig) String() string            { return proto.CompactTextString(m) }
func (*AccountConfig) ProtoMessage()               {}
func (*AccountConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{6} }

func (m *AccountConfig) GetSignature() uint32 {
	if m != nil {
		return m.Signature
	}
	return 0
}

func (m *AccountConfig) GetEncrypt() uint32 {
	if m != nil {
		return m.Encrypt
	}
	return 0
}

func (m *AccountConfig) GetKeyDir() string {
	if m != nil {
		return m.KeyDir
	}
	return ""
}

func (m *AccountConfig) GetTestPassphrase() string {
	if m != nil {
		return m.TestPassphrase
	}
	return ""
}

type Influxdb struct {
	// Influxdb host
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Influxdb db name
	Db string `protobuf:"bytes,2,opt,name=db,proto3" json:"db,omitempty"`
	// Influxdb username
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// Influxdb password
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *Influxdb) Reset()                    { *m = Influxdb{} }
func (m *Influxdb) String() string            { return proto.CompactTextString(m) }
func (*Influxdb) ProtoMessage()               {}
func (*Influxdb) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{7} }

func (m *Influxdb) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Influxdb) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *Influxdb) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Influxdb) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Metrics struct {
	Enable bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (m *Metrics) Reset()                    { *m = Metrics{} }
func (m *Metrics) String() string            { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()               {}
func (*Metrics) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{8} }

func (m *Metrics) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func init() {
	proto.RegisterType((*Config)(nil), "nebletpb.Config")
	proto.RegisterType((*P2PConfig)(nil), "nebletpb.P2PConfig")
	proto.RegisterType((*RPCConfig)(nil), "nebletpb.RPCConfig")
	proto.RegisterType((*PowConfig)(nil), "nebletpb.PowConfig")
	proto.RegisterType((*DPoSConfig)(nil), "nebletpb.DPoSConfig")
	proto.RegisterType((*StorageConfig)(nil), "nebletpb.StorageConfig")
	proto.RegisterType((*AccountConfig)(nil), "nebletpb.AccountConfig")
	proto.RegisterType((*Influxdb)(nil), "nebletpb.Influxdb")
	proto.RegisterType((*Metrics)(nil), "nebletpb.Metrics")
}

func init() { proto.RegisterFile("config.proto", fileDescriptorConfig) }

var fileDescriptorConfig = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xe1, 0x6e, 0xd3, 0x30,
	0x10, 0xc7, 0xd5, 0xae, 0x34, 0xc9, 0x8d, 0x0c, 0x61, 0x26, 0x16, 0x10, 0x1f, 0x20, 0x12, 0x5a,
	0xa5, 0x49, 0x15, 0x94, 0x27, 0x40, 0xdb, 0x07, 0xf6, 0x01, 0x29, 0xf2, 0x1e, 0xa0, 0x72, 0x12,
	0xb7, 0xb5, 0xd6, 0xda, 0x96, 0xed, 0x52, 0xfa, 0x08, 0x3c, 0x08, 0x2f, 0xc7, 0x53, 0x20, 0x5f,
	0xec, 0x64, 0x1b, 0x12, 0xdf, 0x7c, 0x77, 0xbf, 0xbb, 0xb3, 0xff, 0xf9, 0x2b, 0xf0, 0xbc, 0x51,
	0x72, 0x25, 0xd6, 0x73, 0x6d, 0x94, 0x53, 0x24, 0x95, 0xbc, 0xde, 0x72, 0xa7, 0xeb, 0xf2, 0xcf,
	0x18, 0xa6, 0xd7, 0x58, 0x22, 0x1f, 0xe1, 0x44, 0x2f, 0x74, 0x31, 0x7a, 0x3f, 0x9a, 0x9d, 0x2e,
	0x5e, 0xcd, 0x23, 0x32, 0xaf, 0x16, 0x55, 0x47, 0x50, 0x5f, 0xf7, 0x98, 0xd1, 0x4d, 0x31, 0x7e,
	0x8a, 0xd1, 0xea, 0x3a, 0x62, 0x46, 0x37, 0x38, 0x4d, 0x1d, 0x8a, 0x93, 0x7f, 0xa6, 0xa9, 0x43,
	0x3f, 0x4d, 0x1d, 0xc8, 0x0c, 0x26, 0xad, 0x56, 0xb6, 0x98, 0x20, 0x77, 0x3e, 0x70, 0x37, 0x95,
	0xba, 0x0b, 0x20, 0x12, 0xe4, 0x33, 0x24, 0xd6, 0x29, 0xc3, 0xd6, 0xbc, 0x78, 0x86, 0xf0, 0xc5,
	0x00, 0xdf, 0x75, 0x85, 0xc0, 0x47, 0xce, 0xb7, 0xb0, 0xa6, 0x51, 0x7b, 0xe9, 0x8a, 0xe9, 0xd3,
	0x96, 0xaf, 0x5d, 0x21, 0xb6, 0x04, 0x8e, 0xcc, 0x21, 0x15, 0x72, 0xb5, 0xdd, 0xff, 0x6c, 0xeb,
	0x22, 0xc1, 0x1e, 0x32, 0xf4, 0xdc, 0x86, 0x0a, 0xed, 0x19, 0x72, 0x05, 0xc9, 0x8e, 0x3b, 0x23,
	0x1a, 0x5b, 0xa4, 0x88, 0xbf, 0x1c, 0xf0, 0xef, 0x5d, 0x81, 0x46, 0xa2, 0xdc, 0x40, 0xd6, 0x8b,
	0x49, 0x08, 0x4c, 0x2c, 0xe7, 0x2d, 0xea, 0x9d, 0x51, 0x3c, 0xfb, 0x9c, 0x56, 0xc6, 0xa1, 0xb8,
	0x39, 0xc5, 0x33, 0x79, 0x03, 0x69, 0xb3, 0x61, 0x42, 0x2e, 0x45, 0x8b, 0x6a, 0xe6, 0x34, 0xc1,
	0xf8, 0xb6, 0x25, 0x05, 0x24, 0x3f, 0xb8, 0xb1, 0x42, 0x49, 0xd4, 0x2f, 0xa7, 0x31, 0x2c, 0x7f,
	0x8f, 0x20, 0xeb, 0x3f, 0x88, 0x1f, 0xc1, 0xb4, 0x58, 0xe2, 0xe8, 0x51, 0x07, 0x32, 0x2d, 0x2a,
	0x3f, 0xfd, 0x12, 0x5e, 0xec, 0x98, 0x64, 0x6b, 0xbe, 0xe3, 0xd2, 0x2d, 0x1f, 0x2c, 0x3f, 0x1b,
	0xd2, 0x08, 0x96, 0x90, 0xfb, 0x19, 0x1b, 0xe7, 0x74, 0x87, 0x75, 0x77, 0x39, 0x65, 0x5a, 0x7c,
	0x73, 0x4e, 0x23, 0xf3, 0x09, 0xce, 0x1f, 0x0c, 0x1b, 0xd0, 0xee, 0x72, 0x64, 0xa8, 0xc5, 0x8e,
	0xf2, 0x12, 0xb2, 0xde, 0x10, 0xe4, 0x2d, 0xa4, 0x8d, 0x12, 0xb2, 0x66, 0x96, 0x07, 0x55, 0xfa,
	0xb8, 0x9c, 0x01, 0x0c, 0x8e, 0xf8, 0x2f, 0x79, 0x05, 0xf9, 0x23, 0x3b, 0x78, 0x78, 0xab, 0x1a,
	0xe6, 0xbc, 0x4c, 0x01, 0x8e, 0x71, 0xf9, 0x6b, 0x04, 0xf9, 0x23, 0x27, 0x90, 0x77, 0x90, 0x59,
	0xb1, 0x96, 0xcc, 0xed, 0x0d, 0x0f, 0x62, 0x0d, 0x09, 0xaf, 0x38, 0x97, 0x8d, 0x39, 0xea, 0x28,
	0x53, 0x0c, 0xc9, 0x05, 0x24, 0xf7, 0xfc, 0xb8, 0x6c, 0x85, 0x41, 0x65, 0x32, 0x3a, 0xbd, 0xe7,
	0xc7, 0x1b, 0x61, 0xbc, 0xc2, 0x8e, 0x5b, 0xb7, 0xd4, 0xcc, 0x5a, 0xbd, 0x31, 0xfe, 0xca, 0x13,
	0x04, 0xce, 0x7c, 0xba, 0xea, 0xb3, 0xe5, 0x0a, 0xd2, 0x68, 0x30, 0x6f, 0x84, 0x8d, 0xb2, 0x2e,
	0x9a, 0xc3, 0x9f, 0xc9, 0x19, 0x8c, 0xdb, 0x1a, 0xd7, 0x66, 0x74, 0xdc, 0xd6, 0xfe, 0x5d, 0x7b,
	0xcb, 0x8d, 0x64, 0x3b, 0x1e, 0x56, 0xf6, 0xb1, 0xaf, 0xf9, 0x7d, 0x07, 0x65, 0xda, 0xb0, 0xad,
	0x8f, 0xcb, 0x0f, 0x90, 0x04, 0x67, 0x92, 0xd7, 0x30, 0xe5, 0x92, 0xd5, 0xdb, 0xee, 0xa5, 0x29,
	0x0d, 0x51, 0x3d, 0xc5, 0xdf, 0xc4, 0x97, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xfb, 0xeb,
	0xbd, 0x36, 0x04, 0x00, 0x00,
}
