// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config.proto

/*
Package nebletpb is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Config
	NetworkConfig
	ChainConfig
	RPCConfig
	MiscConfig
	StatsConfig
	InfluxdbConfig
*/
package nebletpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Supported signature cipher list.
type ChainConfig_SignatureCiphers int32

const (
	ChainConfig_ECC_SECP256K1 ChainConfig_SignatureCiphers = 0
)

var ChainConfig_SignatureCiphers_name = map[int32]string{
	0: "ECC_SECP256K1",
}
var ChainConfig_SignatureCiphers_value = map[string]int32{
	"ECC_SECP256K1": 0,
}

func (x ChainConfig_SignatureCiphers) String() string {
	return proto.EnumName(ChainConfig_SignatureCiphers_name, int32(x))
}
func (ChainConfig_SignatureCiphers) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorConfig, []int{2, 0}
}

// Reporting modules.
type StatsConfig_ReportingModule int32

const (
	StatsConfig_Influxdb StatsConfig_ReportingModule = 0
)

var StatsConfig_ReportingModule_name = map[int32]string{
	0: "Influxdb",
}
var StatsConfig_ReportingModule_value = map[string]int32{
	"Influxdb": 0,
}

func (x StatsConfig_ReportingModule) String() string {
	return proto.EnumName(StatsConfig_ReportingModule_name, int32(x))
}
func (StatsConfig_ReportingModule) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorConfig, []int{5, 0}
}

// Neblet global configurations.
type Config struct {
	// Network config.
	Network *NetworkConfig `protobuf:"bytes,1,opt,name=network" json:"network,omitempty"`
	// Chain config.
	Chain *ChainConfig `protobuf:"bytes,2,opt,name=chain" json:"chain,omitempty"`
	// RPC config.
	Rpc *RPCConfig `protobuf:"bytes,3,opt,name=rpc" json:"rpc,omitempty"`
	// Stats config.
	Stats *StatsConfig `protobuf:"bytes,100,opt,name=stats" json:"stats,omitempty"`
	// Misc config.
	Misc *MiscConfig `protobuf:"bytes,101,opt,name=misc" json:"misc,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{0} }

func (m *Config) GetNetwork() *NetworkConfig {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *Config) GetChain() *ChainConfig {
	if m != nil {
		return m.Chain
	}
	return nil
}

func (m *Config) GetRpc() *RPCConfig {
	if m != nil {
		return m.Rpc
	}
	return nil
}

func (m *Config) GetStats() *StatsConfig {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Config) GetMisc() *MiscConfig {
	if m != nil {
		return m.Misc
	}
	return nil
}

type NetworkConfig struct {
	// Neb seed node address.
	Seed []string `protobuf:"bytes,1,rep,name=seed" json:"seed,omitempty"`
	// Listen addresses.
	Listen uint32 `protobuf:"varint,2,opt,name=listen,proto3" json:"listen,omitempty"`
	// Network node privateKey address. If nil, generate a new node.
	PrivateKey string `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (m *NetworkConfig) Reset()                    { *m = NetworkConfig{} }
func (m *NetworkConfig) String() string            { return proto.CompactTextString(m) }
func (*NetworkConfig) ProtoMessage()               {}
func (*NetworkConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{1} }

func (m *NetworkConfig) GetSeed() []string {
	if m != nil {
		return m.Seed
	}
	return nil
}

func (m *NetworkConfig) GetListen() uint32 {
	if m != nil {
		return m.Listen
	}
	return 0
}

func (m *NetworkConfig) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type ChainConfig struct {
	// ChainID.
	ChainId uint32 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Data dir.
	Datadir string `protobuf:"bytes,11,opt,name=datadir,proto3" json:"datadir,omitempty"`
	// Key dir.
	Keydir string `protobuf:"bytes,12,opt,name=keydir,proto3" json:"keydir,omitempty"`
	// Coinbase.
	Coinbase string `protobuf:"bytes,21,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	// Miner.
	Miner string `protobuf:"bytes,22,opt,name=miner,proto3" json:"miner,omitempty"`
	// Passphrase.
	Passphrase string `protobuf:"bytes,23,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	// GasPrice.
	Gasprice         string                         `protobuf:"bytes,24,opt,name=gasprice,proto3" json:"gasprice,omitempty"`
	SignatureCiphers []ChainConfig_SignatureCiphers `protobuf:"varint,25,rep,packed,name=signature_ciphers,json=signatureCiphers,enum=nebletpb.ChainConfig_SignatureCiphers" json:"signature_ciphers,omitempty"`
}

func (m *ChainConfig) Reset()                    { *m = ChainConfig{} }
func (m *ChainConfig) String() string            { return proto.CompactTextString(m) }
func (*ChainConfig) ProtoMessage()               {}
func (*ChainConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{2} }

func (m *ChainConfig) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *ChainConfig) GetDatadir() string {
	if m != nil {
		return m.Datadir
	}
	return ""
}

func (m *ChainConfig) GetKeydir() string {
	if m != nil {
		return m.Keydir
	}
	return ""
}

func (m *ChainConfig) GetCoinbase() string {
	if m != nil {
		return m.Coinbase
	}
	return ""
}

func (m *ChainConfig) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *ChainConfig) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *ChainConfig) GetGasprice() string {
	if m != nil {
		return m.Gasprice
	}
	return ""
}

func (m *ChainConfig) GetSignatureCiphers() []ChainConfig_SignatureCiphers {
	if m != nil {
		return m.SignatureCiphers
	}
	return nil
}

type RPCConfig struct {
	// RPC listen addresses.
	RpcListen uint32 `protobuf:"varint,1,opt,name=rpc_listen,json=rpcListen,proto3" json:"rpc_listen,omitempty"`
	// HTTP listen addresses.
	HttpListen uint32 `protobuf:"varint,2,opt,name=http_listen,json=httpListen,proto3" json:"http_listen,omitempty"`
}

func (m *RPCConfig) Reset()                    { *m = RPCConfig{} }
func (m *RPCConfig) String() string            { return proto.CompactTextString(m) }
func (*RPCConfig) ProtoMessage()               {}
func (*RPCConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{3} }

func (m *RPCConfig) GetRpcListen() uint32 {
	if m != nil {
		return m.RpcListen
	}
	return 0
}

func (m *RPCConfig) GetHttpListen() uint32 {
	if m != nil {
		return m.HttpListen
	}
	return 0
}

type MiscConfig struct {
	// Default encryption ciper when create new keystore file.
	DefaultKeystoreFileCiper string `protobuf:"bytes,1,opt,name=default_keystore_file_ciper,json=defaultKeystoreFileCiper,proto3" json:"default_keystore_file_ciper,omitempty"`
}

func (m *MiscConfig) Reset()                    { *m = MiscConfig{} }
func (m *MiscConfig) String() string            { return proto.CompactTextString(m) }
func (*MiscConfig) ProtoMessage()               {}
func (*MiscConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{4} }

func (m *MiscConfig) GetDefaultKeystoreFileCiper() string {
	if m != nil {
		return m.DefaultKeystoreFileCiper
	}
	return ""
}

type StatsConfig struct {
	// Enable metrics or not.
	EnableMetrics   bool                          `protobuf:"varint,1,opt,name=enable_metrics,json=enableMetrics,proto3" json:"enable_metrics,omitempty"`
	ReportingModule []StatsConfig_ReportingModule `protobuf:"varint,2,rep,packed,name=reporting_module,json=reportingModule,enum=nebletpb.StatsConfig_ReportingModule" json:"reporting_module,omitempty"`
	// Influxdb config.
	Influxdb *InfluxdbConfig `protobuf:"bytes,11,opt,name=influxdb" json:"influxdb,omitempty"`
}

func (m *StatsConfig) Reset()                    { *m = StatsConfig{} }
func (m *StatsConfig) String() string            { return proto.CompactTextString(m) }
func (*StatsConfig) ProtoMessage()               {}
func (*StatsConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{5} }

func (m *StatsConfig) GetEnableMetrics() bool {
	if m != nil {
		return m.EnableMetrics
	}
	return false
}

func (m *StatsConfig) GetReportingModule() []StatsConfig_ReportingModule {
	if m != nil {
		return m.ReportingModule
	}
	return nil
}

func (m *StatsConfig) GetInfluxdb() *InfluxdbConfig {
	if m != nil {
		return m.Influxdb
	}
	return nil
}

type InfluxdbConfig struct {
	// Host.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Port.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Database name.
	Db string `protobuf:"bytes,3,opt,name=db,proto3" json:"db,omitempty"`
	// Auth user.
	User string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	// Auth password.
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *InfluxdbConfig) Reset()                    { *m = InfluxdbConfig{} }
func (m *InfluxdbConfig) String() string            { return proto.CompactTextString(m) }
func (*InfluxdbConfig) ProtoMessage()               {}
func (*InfluxdbConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{6} }

func (m *InfluxdbConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *InfluxdbConfig) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *InfluxdbConfig) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *InfluxdbConfig) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *InfluxdbConfig) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "nebletpb.Config")
	proto.RegisterType((*NetworkConfig)(nil), "nebletpb.NetworkConfig")
	proto.RegisterType((*ChainConfig)(nil), "nebletpb.ChainConfig")
	proto.RegisterType((*RPCConfig)(nil), "nebletpb.RPCConfig")
	proto.RegisterType((*MiscConfig)(nil), "nebletpb.MiscConfig")
	proto.RegisterType((*StatsConfig)(nil), "nebletpb.StatsConfig")
	proto.RegisterType((*InfluxdbConfig)(nil), "nebletpb.InfluxdbConfig")
	proto.RegisterEnum("nebletpb.ChainConfig_SignatureCiphers", ChainConfig_SignatureCiphers_name, ChainConfig_SignatureCiphers_value)
	proto.RegisterEnum("nebletpb.StatsConfig_ReportingModule", StatsConfig_ReportingModule_name, StatsConfig_ReportingModule_value)
}

func init() { proto.RegisterFile("config.proto", fileDescriptorConfig) }

var fileDescriptorConfig = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xdb, 0x6e, 0x1a, 0x3d,
	0x10, 0xc7, 0x03, 0xe4, 0x00, 0x43, 0x20, 0xc4, 0x5f, 0x0e, 0xce, 0x57, 0xb5, 0x89, 0x56, 0xa2,
	0x42, 0xaa, 0x84, 0x14, 0x7a, 0xb8, 0xeb, 0xd5, 0x2a, 0x95, 0x22, 0x9a, 0x2a, 0x5a, 0x6e, 0x2b,
	0xad, 0xf6, 0x30, 0x80, 0x95, 0x65, 0x77, 0x65, 0x9b, 0x26, 0x79, 0xbf, 0xbe, 0x46, 0x6f, 0xfb,
	0x1c, 0x95, 0xc7, 0x5e, 0x08, 0x28, 0x77, 0x9e, 0xff, 0xfc, 0xfc, 0x67, 0xe7, 0x60, 0xe0, 0x30,
	0x29, 0xf2, 0xa9, 0x98, 0x0d, 0x4b, 0x59, 0xe8, 0x82, 0x35, 0x73, 0x8c, 0x33, 0xd4, 0x65, 0xec,
	0xfd, 0xad, 0xc1, 0xbe, 0x4f, 0x29, 0x76, 0x0d, 0x07, 0x39, 0xea, 0xc7, 0x42, 0x3e, 0xf0, 0xda,
	0x55, 0x6d, 0xd0, 0x1e, 0x9d, 0x0f, 0x2b, 0x6c, 0xf8, 0xc3, 0x26, 0x2c, 0x19, 0x54, 0x1c, 0xfb,
	0x00, 0x7b, 0xc9, 0x3c, 0x12, 0x39, 0xaf, 0xd3, 0x85, 0xd3, 0xf5, 0x05, 0xdf, 0xc8, 0x0e, 0xb7,
	0x0c, 0xeb, 0x43, 0x43, 0x96, 0x09, 0x6f, 0x10, 0xfa, 0xdf, 0x1a, 0x0d, 0xee, 0x7d, 0x07, 0x9a,
	0xbc, 0xf1, 0x54, 0x3a, 0xd2, 0x8a, 0xa7, 0xdb, 0x9e, 0x13, 0x23, 0x57, 0x9e, 0xc4, 0xb0, 0x01,
	0xec, 0x2e, 0x84, 0x4a, 0x38, 0x12, 0x7b, 0xb2, 0x66, 0xef, 0x84, 0x4a, 0x1c, 0x4a, 0x84, 0xf7,
	0x13, 0x3a, 0x1b, 0x45, 0x30, 0x06, 0xbb, 0x0a, 0x31, 0xe5, 0xb5, 0xab, 0xc6, 0xa0, 0x15, 0xd0,
	0x99, 0x9d, 0xc1, 0x7e, 0x26, 0x94, 0x46, 0x5b, 0x50, 0x27, 0x70, 0x11, 0xbb, 0x84, 0x76, 0x29,
	0xc5, 0xaf, 0x48, 0x63, 0xf8, 0x80, 0xcf, 0x54, 0x42, 0x2b, 0x00, 0x27, 0x8d, 0xf1, 0xd9, 0xfb,
	0x5d, 0x87, 0xf6, 0x8b, 0x92, 0xd9, 0x05, 0x34, 0xa9, 0xe8, 0x50, 0xa4, 0xd4, 0xcc, 0x4e, 0x70,
	0x40, 0xf1, 0x6d, 0xca, 0x38, 0x1c, 0xa4, 0x91, 0x8e, 0x52, 0x21, 0x79, 0x9b, 0x7c, 0xaa, 0xd0,
	0xfc, 0xfa, 0x03, 0x3e, 0x9b, 0xc4, 0x21, 0x25, 0x5c, 0xc4, 0xfe, 0x87, 0x66, 0x52, 0x88, 0x3c,
	0x8e, 0x14, 0xf2, 0x53, 0xca, 0xac, 0x62, 0x76, 0x02, 0x7b, 0x0b, 0x91, 0xa3, 0xe4, 0x67, 0x94,
	0xb0, 0x01, 0x7b, 0x07, 0x50, 0x46, 0x4a, 0x95, 0x73, 0x69, 0xee, 0x9c, 0xbb, 0xcf, 0x5d, 0x29,
	0xc6, 0x71, 0x16, 0xa9, 0x52, 0x8a, 0x04, 0x39, 0xb7, 0x8e, 0x55, 0xcc, 0x26, 0x70, 0xac, 0xc4,
	0x2c, 0x8f, 0xf4, 0x52, 0x62, 0x98, 0x88, 0x72, 0x8e, 0x52, 0xf1, 0x8b, 0xab, 0xc6, 0xa0, 0x3b,
	0x7a, 0xff, 0xea, 0x7c, 0x87, 0x93, 0x0a, 0xf7, 0x2d, 0x1d, 0xf4, 0xd4, 0x96, 0xe2, 0xf5, 0xa1,
	0xb7, 0x4d, 0xb1, 0x63, 0xe8, 0xdc, 0xf8, 0x7e, 0x38, 0xb9, 0xf1, 0xef, 0x47, 0x9f, 0xbf, 0x8c,
	0xaf, 0x7b, 0x3b, 0xde, 0x18, 0x5a, 0xab, 0x6d, 0x60, 0x6f, 0x01, 0x64, 0x99, 0x84, 0x6e, 0x20,
	0xb6, 0x8b, 0x2d, 0x59, 0x26, 0xdf, 0x57, 0x33, 0x99, 0x6b, 0x5d, 0x86, 0x1b, 0x03, 0x03, 0x23,
	0x59, 0xc0, 0x1b, 0x03, 0xac, 0xb7, 0x80, 0x7d, 0x85, 0x37, 0x29, 0x4e, 0xa3, 0x65, 0xa6, 0xcd,
	0x08, 0x95, 0x2e, 0x24, 0x86, 0x53, 0x91, 0x51, 0x89, 0x28, 0xc9, 0xbe, 0x15, 0x70, 0x87, 0x8c,
	0x1d, 0xf1, 0x4d, 0x64, 0xe6, 0x73, 0x51, 0x7a, 0x7f, 0x6a, 0xd0, 0x7e, 0xb1, 0x7f, 0xac, 0x0f,
	0x5d, 0xcc, 0xa3, 0x38, 0xc3, 0x70, 0x81, 0x5a, 0x8a, 0x44, 0x91, 0x43, 0x33, 0xe8, 0x58, 0xf5,
	0xce, 0x8a, 0xec, 0x1e, 0x7a, 0x12, 0xcb, 0x42, 0x6a, 0x91, 0xcf, 0xc2, 0x45, 0x91, 0x2e, 0x33,
	0xe4, 0x75, 0xea, 0x65, 0xff, 0xd5, 0xbd, 0x1e, 0x06, 0x15, 0x7d, 0x47, 0x70, 0x70, 0x24, 0x37,
	0x05, 0xf6, 0x09, 0x9a, 0x22, 0x9f, 0x66, 0xcb, 0xa7, 0x34, 0xa6, 0xfd, 0x69, 0x8f, 0xf8, 0xda,
	0xe9, 0xd6, 0x65, 0xdc, 0xe6, 0xaf, 0x48, 0xef, 0x12, 0x8e, 0xb6, 0x9c, 0xd9, 0x21, 0x34, 0x2b,
	0xbc, 0xb7, 0xe3, 0x3d, 0x41, 0x77, 0xf3, 0xb2, 0x79, 0x1f, 0xf3, 0x42, 0x69, 0xd7, 0x19, 0x3a,
	0x1b, 0xcd, 0x98, 0xb8, 0x66, 0xd3, 0x99, 0x75, 0xa1, 0x9e, 0xc6, 0xee, 0x49, 0xd4, 0xd3, 0xd8,
	0x30, 0x4b, 0x85, 0x92, 0xef, 0xda, 0x7b, 0xe6, 0x6c, 0xf6, 0xcd, 0x6c, 0xdf, 0x63, 0x21, 0x53,
	0xbe, 0x67, 0xf7, 0xad, 0x8a, 0xe3, 0x7d, 0xfa, 0x4b, 0xfa, 0xf8, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x2c, 0x91, 0xb0, 0xd7, 0xa2, 0x04, 0x00, 0x00,
}
