// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api_rpc.proto

/*
Package rpcpb is a generated protocol buffer package.

It is generated from these files:
	api_rpc.proto

It has these top-level messages:
	GetNebStateRequest
	NodeInfoRequest
	NodeInfoResponse
	StatisticsNodeInfoResponse
	RouteTable
	GetNebStateResponse
	AccountsRequest
	AccountsResponse
	GetAccountStateRequest
	GetAccountStateResponse
	GetDynastyRequest
	GetDynastyResponse
	SendTransactionRequest
	CallRequest
	SendRawTransactionRequest
	SendTransactionResponse
	GetBlockByHashRequest
	GetTransactionByHashRequest
	BlockDumpRequest
	BlockDumpResponse
	TransactionReceiptResponse
	NewAccountRequest
	NewAccountResponse
	UnlockAccountRequest
	UnlockAccountResponse
	LockAccountRequest
	LockAccountResponse
	SignTransactionRequest
	SignTransactionResponse
	SendTransactionPassphraseRequest
	SendTransactionPassphraseResponse
*/
package rpcpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import corepb "github.com/nebulasio/go-nebulas/core/pb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Request message of GetNebState rpc.
type GetNebStateRequest struct {
}

func (m *GetNebStateRequest) Reset()                    { *m = GetNebStateRequest{} }
func (m *GetNebStateRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNebStateRequest) ProtoMessage()               {}
func (*GetNebStateRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{0} }

// Request message of NodeInfo rpc.
type NodeInfoRequest struct {
}

func (m *NodeInfoRequest) Reset()                    { *m = NodeInfoRequest{} }
func (m *NodeInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*NodeInfoRequest) ProtoMessage()               {}
func (*NodeInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{1} }

// Response message of node info.
type NodeInfoResponse struct {
	// the node ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the block chainID.
	ChainId uint32 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// the node version.
	Version uint32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Number of peers currenly connected.
	PeerCount uint32 `protobuf:"varint,4,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	// the node synchronized status.
	Synchronized bool `protobuf:"varint,5,opt,name=synchronized,proto3" json:"synchronized,omitempty"`
	// the node route table bucket size.
	BucketSize int32 `protobuf:"varint,6,opt,name=bucket_size,json=bucketSize,proto3" json:"bucket_size,omitempty"`
	// the node relay cache size.
	RelayCacheSize int32 `protobuf:"varint,7,opt,name=relay_cache_size,json=relayCacheSize,proto3" json:"relay_cache_size,omitempty"`
	// the node stream store size.
	StreamStoreSize int32 `protobuf:"varint,8,opt,name=stream_store_size,json=streamStoreSize,proto3" json:"stream_store_size,omitempty"`
	// the node stream store extend size.
	StreamStoreExtendSize int32 `protobuf:"varint,9,opt,name=stream_store_extend_size,json=streamStoreExtendSize,proto3" json:"stream_store_extend_size,omitempty"`
	// the network protocol version.
	ProtocolVersion string        `protobuf:"bytes,10,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RouteTable      []*RouteTable `protobuf:"bytes,11,rep,name=route_table,json=routeTable" json:"route_table,omitempty"`
}

func (m *NodeInfoResponse) Reset()                    { *m = NodeInfoResponse{} }
func (m *NodeInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeInfoResponse) ProtoMessage()               {}
func (*NodeInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{2} }

func (m *NodeInfoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeInfoResponse) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *NodeInfoResponse) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *NodeInfoResponse) GetPeerCount() uint32 {
	if m != nil {
		return m.PeerCount
	}
	return 0
}

func (m *NodeInfoResponse) GetSynchronized() bool {
	if m != nil {
		return m.Synchronized
	}
	return false
}

func (m *NodeInfoResponse) GetBucketSize() int32 {
	if m != nil {
		return m.BucketSize
	}
	return 0
}

func (m *NodeInfoResponse) GetRelayCacheSize() int32 {
	if m != nil {
		return m.RelayCacheSize
	}
	return 0
}

func (m *NodeInfoResponse) GetStreamStoreSize() int32 {
	if m != nil {
		return m.StreamStoreSize
	}
	return 0
}

func (m *NodeInfoResponse) GetStreamStoreExtendSize() int32 {
	if m != nil {
		return m.StreamStoreExtendSize
	}
	return 0
}

func (m *NodeInfoResponse) GetProtocolVersion() string {
	if m != nil {
		return m.ProtocolVersion
	}
	return ""
}

func (m *NodeInfoResponse) GetRouteTable() []*RouteTable {
	if m != nil {
		return m.RouteTable
	}
	return nil
}

type StatisticsNodeInfoResponse struct {
	NodeID    string `protobuf:"bytes,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Height    uint64 `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	Hash      string `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	PeerCount uint32 `protobuf:"varint,4,opt,name=PeerCount,proto3" json:"PeerCount,omitempty"`
}

func (m *StatisticsNodeInfoResponse) Reset()                    { *m = StatisticsNodeInfoResponse{} }
func (m *StatisticsNodeInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*StatisticsNodeInfoResponse) ProtoMessage()               {}
func (*StatisticsNodeInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{3} }

func (m *StatisticsNodeInfoResponse) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *StatisticsNodeInfoResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *StatisticsNodeInfoResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *StatisticsNodeInfoResponse) GetPeerCount() uint32 {
	if m != nil {
		return m.PeerCount
	}
	return 0
}

type RouteTable struct {
	Id      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address []string `protobuf:"bytes,2,rep,name=address" json:"address,omitempty"`
}

func (m *RouteTable) Reset()                    { *m = RouteTable{} }
func (m *RouteTable) String() string            { return proto.CompactTextString(m) }
func (*RouteTable) ProtoMessage()               {}
func (*RouteTable) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{4} }

func (m *RouteTable) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RouteTable) GetAddress() []string {
	if m != nil {
		return m.Address
	}
	return nil
}

// Response message of GetNebState rpc.
type GetNebStateResponse struct {
	// Block chain id
	ChainId uint32 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Current neb tail hash
	Tail string `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	// Neb coinbase
	Coinbase string `protobuf:"bytes,3,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	// Number of peers currenly connected
	PeerCount uint32 `protobuf:"varint,4,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	// Neb mine status, minging is true ,otherwise false
	IsMining bool `protobuf:"varint,5,opt,name=is_mining,json=isMining,proto3" json:"is_mining,omitempty"`
	// The current neb protocol version.
	ProtocolVersion string `protobuf:"bytes,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// The peer sync status.
	Synchronized bool `protobuf:"varint,7,opt,name=synchronized,proto3" json:"synchronized,omitempty"`
}

func (m *GetNebStateResponse) Reset()                    { *m = GetNebStateResponse{} }
func (m *GetNebStateResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNebStateResponse) ProtoMessage()               {}
func (*GetNebStateResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{5} }

func (m *GetNebStateResponse) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *GetNebStateResponse) GetTail() string {
	if m != nil {
		return m.Tail
	}
	return ""
}

func (m *GetNebStateResponse) GetCoinbase() string {
	if m != nil {
		return m.Coinbase
	}
	return ""
}

func (m *GetNebStateResponse) GetPeerCount() uint32 {
	if m != nil {
		return m.PeerCount
	}
	return 0
}

func (m *GetNebStateResponse) GetIsMining() bool {
	if m != nil {
		return m.IsMining
	}
	return false
}

func (m *GetNebStateResponse) GetProtocolVersion() string {
	if m != nil {
		return m.ProtocolVersion
	}
	return ""
}

func (m *GetNebStateResponse) GetSynchronized() bool {
	if m != nil {
		return m.Synchronized
	}
	return false
}

// Request message of Accounts rpc.
type AccountsRequest struct {
}

func (m *AccountsRequest) Reset()                    { *m = AccountsRequest{} }
func (m *AccountsRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountsRequest) ProtoMessage()               {}
func (*AccountsRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{6} }

// Response message of Accounts rpc.
type AccountsResponse struct {
	// Account list
	Addresses []string `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *AccountsResponse) Reset()                    { *m = AccountsResponse{} }
func (m *AccountsResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountsResponse) ProtoMessage()               {}
func (*AccountsResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{7} }

func (m *AccountsResponse) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

// Request message of GetAccountState rpc.
type GetAccountStateRequest struct {
	// Hex string of the account addresss.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Hex string block number, or one of "latest", "earliest" or "pending". If not specified, use "latest".
	Block string `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
}

func (m *GetAccountStateRequest) Reset()                    { *m = GetAccountStateRequest{} }
func (m *GetAccountStateRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAccountStateRequest) ProtoMessage()               {}
func (*GetAccountStateRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{8} }

func (m *GetAccountStateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetAccountStateRequest) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

// Response message of GetAccountState rpc.
type GetAccountStateResponse struct {
	// Current balance in unit of 1/(10^18) nas.
	Balance string `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	// Current transaction count.
	Nonce string `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *GetAccountStateResponse) Reset()                    { *m = GetAccountStateResponse{} }
func (m *GetAccountStateResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAccountStateResponse) ProtoMessage()               {}
func (*GetAccountStateResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{9} }

func (m *GetAccountStateResponse) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *GetAccountStateResponse) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

// Request message of GetDynastyRequest rpc.
type GetDynastyRequest struct {
}

func (m *GetDynastyRequest) Reset()                    { *m = GetDynastyRequest{} }
func (m *GetDynastyRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDynastyRequest) ProtoMessage()               {}
func (*GetDynastyRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{10} }

// Response message of GetDynastyRequest rpc
type GetDynastyResponse struct {
	Delegatees []string `protobuf:"bytes,1,rep,name=delegatees" json:"delegatees,omitempty"`
}

func (m *GetDynastyResponse) Reset()                    { *m = GetDynastyResponse{} }
func (m *GetDynastyResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDynastyResponse) ProtoMessage()               {}
func (*GetDynastyResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{11} }

func (m *GetDynastyResponse) GetDelegatees() []string {
	if m != nil {
		return m.Delegatees
	}
	return nil
}

// Request message of SendTransaction rpc.
type SendTransactionRequest struct {
	// Hex string of the sender account addresss.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Hex string of the receiver account addresss.
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Amount of value sending with this transaction.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Transaction nonce.
	Nonce uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// contract source code.
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// the params of contract.
	Args string `protobuf:"bytes,6,opt,name=args,proto3" json:"args,omitempty"`
	// gasPrice sending with this transaction.
	GasPrice string `protobuf:"bytes,7,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// gasLimit sending with this transaction.
	GasLimit string `protobuf:"bytes,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
}

func (m *SendTransactionRequest) Reset()                    { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()               {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{12} }

func (m *SendTransactionRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendTransactionRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SendTransactionRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SendTransactionRequest) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *SendTransactionRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SendTransactionRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *SendTransactionRequest) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *SendTransactionRequest) GetGasLimit() string {
	if m != nil {
		return m.GasLimit
	}
	return ""
}

type CallRequest struct {
	// Hex string of the sender account addresss.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Hex string of the receiver account addresss.
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Transaction nonce.
	Nonce uint64 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// call contract function name
	Function string `protobuf:"bytes,4,opt,name=function,proto3" json:"function,omitempty"`
	// the params of contract.
	Args string `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	// gasPrice sending with this transaction.
	GasPrice string `protobuf:"bytes,6,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// gasLimit sending with this transaction.
	GasLimit string `protobuf:"bytes,7,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Value    string `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *CallRequest) Reset()                    { *m = CallRequest{} }
func (m *CallRequest) String() string            { return proto.CompactTextString(m) }
func (*CallRequest) ProtoMessage()               {}
func (*CallRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{13} }

func (m *CallRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *CallRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *CallRequest) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *CallRequest) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *CallRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *CallRequest) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *CallRequest) GetGasLimit() string {
	if m != nil {
		return m.GasLimit
	}
	return ""
}

func (m *CallRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Request message of SendRawTransactionRequest rpc.
type SendRawTransactionRequest struct {
	// Signed data of transaction
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *SendRawTransactionRequest) Reset()                    { *m = SendRawTransactionRequest{} }
func (m *SendRawTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*SendRawTransactionRequest) ProtoMessage()               {}
func (*SendRawTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{14} }

func (m *SendRawTransactionRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Response message of SendTransaction rpc.
type SendTransactionResponse struct {
	// Hex string of transaction hash.
	Txhash          string `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (m *SendTransactionResponse) Reset()                    { *m = SendTransactionResponse{} }
func (m *SendTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*SendTransactionResponse) ProtoMessage()               {}
func (*SendTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{15} }

func (m *SendTransactionResponse) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *SendTransactionResponse) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

// Request message of GetBlockByHash rpc.
type GetBlockByHashRequest struct {
	// Hex string of block hash.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *GetBlockByHashRequest) Reset()                    { *m = GetBlockByHashRequest{} }
func (m *GetBlockByHashRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockByHashRequest) ProtoMessage()               {}
func (*GetBlockByHashRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{16} }

func (m *GetBlockByHashRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// Request message of GetTransactionByHash rpc.
type GetTransactionByHashRequest struct {
	// Hex string of transaction hash.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *GetTransactionByHashRequest) Reset()         { *m = GetTransactionByHashRequest{} }
func (m *GetTransactionByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionByHashRequest) ProtoMessage()    {}
func (*GetTransactionByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorApiRpc, []int{17}
}

func (m *GetTransactionByHashRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// Request message of BlockDump.
type BlockDumpRequest struct {
	// the count of blocks to dump before current tail.
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *BlockDumpRequest) Reset()                    { *m = BlockDumpRequest{} }
func (m *BlockDumpRequest) String() string            { return proto.CompactTextString(m) }
func (*BlockDumpRequest) ProtoMessage()               {}
func (*BlockDumpRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{18} }

func (m *BlockDumpRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// Response message of BlockDump.
type BlockDumpResponse struct {
	// block dump info.
	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *BlockDumpResponse) Reset()                    { *m = BlockDumpResponse{} }
func (m *BlockDumpResponse) String() string            { return proto.CompactTextString(m) }
func (*BlockDumpResponse) ProtoMessage()               {}
func (*BlockDumpResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{19} }

func (m *BlockDumpResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Response message of TransactionReceipt.
type TransactionReceiptResponse struct {
	// Hex string of tx hash.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Hex string of the sender account addresss.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// Hex string of the receiver account addresss.
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// Transaction nonce.
	Nonce           uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp       int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data            string `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	ChainId         uint32 `protobuf:"varint,7,opt,name=chainId,proto3" json:"chainId,omitempty"`
	ContractAddress string `protobuf:"bytes,8,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (m *TransactionReceiptResponse) Reset()         { *m = TransactionReceiptResponse{} }
func (m *TransactionReceiptResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionReceiptResponse) ProtoMessage()    {}
func (*TransactionReceiptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorApiRpc, []int{20}
}

func (m *TransactionReceiptResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *TransactionReceiptResponse) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransactionReceiptResponse) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionReceiptResponse) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionReceiptResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionReceiptResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TransactionReceiptResponse) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *TransactionReceiptResponse) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

type NewAccountRequest struct {
	Passphrase string `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
}

func (m *NewAccountRequest) Reset()                    { *m = NewAccountRequest{} }
func (m *NewAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*NewAccountRequest) ProtoMessage()               {}
func (*NewAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{21} }

func (m *NewAccountRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type NewAccountResponse struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *NewAccountResponse) Reset()                    { *m = NewAccountResponse{} }
func (m *NewAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*NewAccountResponse) ProtoMessage()               {}
func (*NewAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{22} }

func (m *NewAccountResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UnlockAccountRequest struct {
	Address    string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Passphrase string `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
}

func (m *UnlockAccountRequest) Reset()                    { *m = UnlockAccountRequest{} }
func (m *UnlockAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*UnlockAccountRequest) ProtoMessage()               {}
func (*UnlockAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{23} }

func (m *UnlockAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UnlockAccountRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type UnlockAccountResponse struct {
	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *UnlockAccountResponse) Reset()                    { *m = UnlockAccountResponse{} }
func (m *UnlockAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*UnlockAccountResponse) ProtoMessage()               {}
func (*UnlockAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{24} }

func (m *UnlockAccountResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type LockAccountRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *LockAccountRequest) Reset()                    { *m = LockAccountRequest{} }
func (m *LockAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*LockAccountRequest) ProtoMessage()               {}
func (*LockAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{25} }

func (m *LockAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type LockAccountResponse struct {
	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *LockAccountResponse) Reset()                    { *m = LockAccountResponse{} }
func (m *LockAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*LockAccountResponse) ProtoMessage()               {}
func (*LockAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{26} }

func (m *LockAccountResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type SignTransactionRequest struct {
	// Hex string of the sender account addresss.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Hex string of the receiver account addresss.
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Amount of value sending with this transaction.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Transaction nonce.
	Nonce uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// contract source code.
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// the params of contract.
	Args string `protobuf:"bytes,6,opt,name=args,proto3" json:"args,omitempty"`
	// gasPrice sending with this transaction.
	GasPrice string `protobuf:"bytes,7,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// gasLimit sending with this transaction.
	GasLimit string `protobuf:"bytes,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
}

func (m *SignTransactionRequest) Reset()                    { *m = SignTransactionRequest{} }
func (m *SignTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*SignTransactionRequest) ProtoMessage()               {}
func (*SignTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{27} }

func (m *SignTransactionRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SignTransactionRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SignTransactionRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SignTransactionRequest) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *SignTransactionRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SignTransactionRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *SignTransactionRequest) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *SignTransactionRequest) GetGasLimit() string {
	if m != nil {
		return m.GasLimit
	}
	return ""
}

type SignTransactionResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *SignTransactionResponse) Reset()                    { *m = SignTransactionResponse{} }
func (m *SignTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*SignTransactionResponse) ProtoMessage()               {}
func (*SignTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiRpc, []int{28} }

func (m *SignTransactionResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendTransactionPassphraseRequest struct {
	// Hex string of the sender account addresss.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Hex string of the receiver account addresss.
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Amount of value sending with this transaction.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Transaction nonce.
	Nonce uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// contract source code.
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// the params of contract.
	Args string `protobuf:"bytes,6,opt,name=args,proto3" json:"args,omitempty"`
	// gasPrice sending with this transaction.
	GasPrice string `protobuf:"bytes,7,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// gasLimit sending with this transaction.
	GasLimit string `protobuf:"bytes,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// from account passphrase
	Passphrase string `protobuf:"bytes,9,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
}

func (m *SendTransactionPassphraseRequest) Reset()         { *m = SendTransactionPassphraseRequest{} }
func (m *SendTransactionPassphraseRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionPassphraseRequest) ProtoMessage()    {}
func (*SendTransactionPassphraseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorApiRpc, []int{29}
}

func (m *SendTransactionPassphraseRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendTransactionPassphraseRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SendTransactionPassphraseRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SendTransactionPassphraseRequest) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *SendTransactionPassphraseRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SendTransactionPassphraseRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *SendTransactionPassphraseRequest) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *SendTransactionPassphraseRequest) GetGasLimit() string {
	if m != nil {
		return m.GasLimit
	}
	return ""
}

func (m *SendTransactionPassphraseRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type SendTransactionPassphraseResponse struct {
	// Hex string of transaction hash.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *SendTransactionPassphraseResponse) Reset()         { *m = SendTransactionPassphraseResponse{} }
func (m *SendTransactionPassphraseResponse) String() string { return proto.CompactTextString(m) }
func (*SendTransactionPassphraseResponse) ProtoMessage()    {}
func (*SendTransactionPassphraseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorApiRpc, []int{30}
}

func (m *SendTransactionPassphraseResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*GetNebStateRequest)(nil), "rpcpb.GetNebStateRequest")
	proto.RegisterType((*NodeInfoRequest)(nil), "rpcpb.NodeInfoRequest")
	proto.RegisterType((*NodeInfoResponse)(nil), "rpcpb.NodeInfoResponse")
	proto.RegisterType((*StatisticsNodeInfoResponse)(nil), "rpcpb.StatisticsNodeInfoResponse")
	proto.RegisterType((*RouteTable)(nil), "rpcpb.RouteTable")
	proto.RegisterType((*GetNebStateResponse)(nil), "rpcpb.GetNebStateResponse")
	proto.RegisterType((*AccountsRequest)(nil), "rpcpb.AccountsRequest")
	proto.RegisterType((*AccountsResponse)(nil), "rpcpb.AccountsResponse")
	proto.RegisterType((*GetAccountStateRequest)(nil), "rpcpb.GetAccountStateRequest")
	proto.RegisterType((*GetAccountStateResponse)(nil), "rpcpb.GetAccountStateResponse")
	proto.RegisterType((*GetDynastyRequest)(nil), "rpcpb.GetDynastyRequest")
	proto.RegisterType((*GetDynastyResponse)(nil), "rpcpb.GetDynastyResponse")
	proto.RegisterType((*SendTransactionRequest)(nil), "rpcpb.SendTransactionRequest")
	proto.RegisterType((*CallRequest)(nil), "rpcpb.CallRequest")
	proto.RegisterType((*SendRawTransactionRequest)(nil), "rpcpb.SendRawTransactionRequest")
	proto.RegisterType((*SendTransactionResponse)(nil), "rpcpb.SendTransactionResponse")
	proto.RegisterType((*GetBlockByHashRequest)(nil), "rpcpb.GetBlockByHashRequest")
	proto.RegisterType((*GetTransactionByHashRequest)(nil), "rpcpb.GetTransactionByHashRequest")
	proto.RegisterType((*BlockDumpRequest)(nil), "rpcpb.BlockDumpRequest")
	proto.RegisterType((*BlockDumpResponse)(nil), "rpcpb.BlockDumpResponse")
	proto.RegisterType((*TransactionReceiptResponse)(nil), "rpcpb.TransactionReceiptResponse")
	proto.RegisterType((*NewAccountRequest)(nil), "rpcpb.NewAccountRequest")
	proto.RegisterType((*NewAccountResponse)(nil), "rpcpb.NewAccountResponse")
	proto.RegisterType((*UnlockAccountRequest)(nil), "rpcpb.UnlockAccountRequest")
	proto.RegisterType((*UnlockAccountResponse)(nil), "rpcpb.UnlockAccountResponse")
	proto.RegisterType((*LockAccountRequest)(nil), "rpcpb.LockAccountRequest")
	proto.RegisterType((*LockAccountResponse)(nil), "rpcpb.LockAccountResponse")
	proto.RegisterType((*SignTransactionRequest)(nil), "rpcpb.SignTransactionRequest")
	proto.RegisterType((*SignTransactionResponse)(nil), "rpcpb.SignTransactionResponse")
	proto.RegisterType((*SendTransactionPassphraseRequest)(nil), "rpcpb.SendTransactionPassphraseRequest")
	proto.RegisterType((*SendTransactionPassphraseResponse)(nil), "rpcpb.SendTransactionPassphraseResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for APIService service

type APIServiceClient interface {
	// Return the state of the neb.
	GetNebState(ctx context.Context, in *GetNebStateRequest, opts ...grpc.CallOption) (*GetNebStateResponse, error)
	// Return the p2p node info.
	NodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoResponse, error)
	// Return the dump info of blockchain.
	BlockDump(ctx context.Context, in *BlockDumpRequest, opts ...grpc.CallOption) (*BlockDumpResponse, error)
	// Accounts return account list.
	Accounts(ctx context.Context, in *AccountsRequest, opts ...grpc.CallOption) (*AccountsResponse, error)
	// Return the state of the account.
	GetAccountState(ctx context.Context, in *GetAccountStateRequest, opts ...grpc.CallOption) (*GetAccountStateResponse, error)
	// Verify, sign, and send the transaction.
	SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error)
	// Call smart contract.
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error)
	// Submit the signed transaction.
	SendRawTransaction(ctx context.Context, in *SendRawTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error)
	// Get block header info by the block hash.
	GetBlockByHash(ctx context.Context, in *GetBlockByHashRequest, opts ...grpc.CallOption) (*corepb.Block, error)
	// Get transactionReceipt info by tansaction hash.
	GetTransactionReceipt(ctx context.Context, in *GetTransactionByHashRequest, opts ...grpc.CallOption) (*TransactionReceiptResponse, error)
	StatisticsNodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*StatisticsNodeInfoResponse, error)
	// NewAccount create a new account with passphrase
	NewAccount(ctx context.Context, in *NewAccountRequest, opts ...grpc.CallOption) (*NewAccountResponse, error)
	// UnlockAccount unlock account with passphrase
	UnlockAccount(ctx context.Context, in *UnlockAccountRequest, opts ...grpc.CallOption) (*UnlockAccountResponse, error)
	// LockAccount lock account
	LockAccount(ctx context.Context, in *LockAccountRequest, opts ...grpc.CallOption) (*LockAccountResponse, error)
	// SignTransaction sign transaction
	SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionResponse, error)
	// SendTransactionWithPassphrase send transaction with passphrase
	SendTransactionWithPassphrase(ctx context.Context, in *SendTransactionPassphraseRequest, opts ...grpc.CallOption) (*SendTransactionPassphraseResponse, error)
	// GetDynasty
	GetDynasty(ctx context.Context, in *GetDynastyRequest, opts ...grpc.CallOption) (*GetDynastyResponse, error)
}

type aPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewAPIServiceClient(cc *grpc.ClientConn) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) GetNebState(ctx context.Context, in *GetNebStateRequest, opts ...grpc.CallOption) (*GetNebStateResponse, error) {
	out := new(GetNebStateResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/GetNebState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) NodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoResponse, error) {
	out := new(NodeInfoResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/NodeInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) BlockDump(ctx context.Context, in *BlockDumpRequest, opts ...grpc.CallOption) (*BlockDumpResponse, error) {
	out := new(BlockDumpResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/BlockDump", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) Accounts(ctx context.Context, in *AccountsRequest, opts ...grpc.CallOption) (*AccountsResponse, error) {
	out := new(AccountsResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/Accounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetAccountState(ctx context.Context, in *GetAccountStateRequest, opts ...grpc.CallOption) (*GetAccountStateResponse, error) {
	out := new(GetAccountStateResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/GetAccountState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error) {
	out := new(SendTransactionResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/SendTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error) {
	out := new(SendTransactionResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/Call", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) SendRawTransaction(ctx context.Context, in *SendRawTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error) {
	out := new(SendTransactionResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/SendRawTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetBlockByHash(ctx context.Context, in *GetBlockByHashRequest, opts ...grpc.CallOption) (*corepb.Block, error) {
	out := new(corepb.Block)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/GetBlockByHash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetTransactionReceipt(ctx context.Context, in *GetTransactionByHashRequest, opts ...grpc.CallOption) (*TransactionReceiptResponse, error) {
	out := new(TransactionReceiptResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/GetTransactionReceipt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) StatisticsNodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*StatisticsNodeInfoResponse, error) {
	out := new(StatisticsNodeInfoResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/StatisticsNodeInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) NewAccount(ctx context.Context, in *NewAccountRequest, opts ...grpc.CallOption) (*NewAccountResponse, error) {
	out := new(NewAccountResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/NewAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) UnlockAccount(ctx context.Context, in *UnlockAccountRequest, opts ...grpc.CallOption) (*UnlockAccountResponse, error) {
	out := new(UnlockAccountResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/UnlockAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) LockAccount(ctx context.Context, in *LockAccountRequest, opts ...grpc.CallOption) (*LockAccountResponse, error) {
	out := new(LockAccountResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/LockAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionResponse, error) {
	out := new(SignTransactionResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/SignTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) SendTransactionWithPassphrase(ctx context.Context, in *SendTransactionPassphraseRequest, opts ...grpc.CallOption) (*SendTransactionPassphraseResponse, error) {
	out := new(SendTransactionPassphraseResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/SendTransactionWithPassphrase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetDynasty(ctx context.Context, in *GetDynastyRequest, opts ...grpc.CallOption) (*GetDynastyResponse, error) {
	out := new(GetDynastyResponse)
	err := grpc.Invoke(ctx, "/rpcpb.APIService/GetDynasty", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for APIService service

type APIServiceServer interface {
	// Return the state of the neb.
	GetNebState(context.Context, *GetNebStateRequest) (*GetNebStateResponse, error)
	// Return the p2p node info.
	NodeInfo(context.Context, *NodeInfoRequest) (*NodeInfoResponse, error)
	// Return the dump info of blockchain.
	BlockDump(context.Context, *BlockDumpRequest) (*BlockDumpResponse, error)
	// Accounts return account list.
	Accounts(context.Context, *AccountsRequest) (*AccountsResponse, error)
	// Return the state of the account.
	GetAccountState(context.Context, *GetAccountStateRequest) (*GetAccountStateResponse, error)
	// Verify, sign, and send the transaction.
	SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionResponse, error)
	// Call smart contract.
	Call(context.Context, *CallRequest) (*SendTransactionResponse, error)
	// Submit the signed transaction.
	SendRawTransaction(context.Context, *SendRawTransactionRequest) (*SendTransactionResponse, error)
	// Get block header info by the block hash.
	GetBlockByHash(context.Context, *GetBlockByHashRequest) (*corepb.Block, error)
	// Get transactionReceipt info by tansaction hash.
	GetTransactionReceipt(context.Context, *GetTransactionByHashRequest) (*TransactionReceiptResponse, error)
	StatisticsNodeInfo(context.Context, *NodeInfoRequest) (*StatisticsNodeInfoResponse, error)
	// NewAccount create a new account with passphrase
	NewAccount(context.Context, *NewAccountRequest) (*NewAccountResponse, error)
	// UnlockAccount unlock account with passphrase
	UnlockAccount(context.Context, *UnlockAccountRequest) (*UnlockAccountResponse, error)
	// LockAccount lock account
	LockAccount(context.Context, *LockAccountRequest) (*LockAccountResponse, error)
	// SignTransaction sign transaction
	SignTransaction(context.Context, *SignTransactionRequest) (*SignTransactionResponse, error)
	// SendTransactionWithPassphrase send transaction with passphrase
	SendTransactionWithPassphrase(context.Context, *SendTransactionPassphraseRequest) (*SendTransactionPassphraseResponse, error)
	// GetDynasty
	GetDynasty(context.Context, *GetDynastyRequest) (*GetDynastyResponse, error)
}

func RegisterAPIServiceServer(s *grpc.Server, srv APIServiceServer) {
	s.RegisterService(&_APIService_serviceDesc, srv)
}

func _APIService_GetNebState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNebStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetNebState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/GetNebState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetNebState(ctx, req.(*GetNebStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_NodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).NodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/NodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).NodeInfo(ctx, req.(*NodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_BlockDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockDumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).BlockDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/BlockDump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).BlockDump(ctx, req.(*BlockDumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_Accounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).Accounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/Accounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).Accounts(ctx, req.(*AccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetAccountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetAccountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/GetAccountState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetAccountState(ctx, req.(*GetAccountStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).SendTransaction(ctx, req.(*SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_SendRawTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRawTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).SendRawTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/SendRawTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).SendRawTransaction(ctx, req.(*SendRawTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/GetBlockByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetBlockByHash(ctx, req.(*GetBlockByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetTransactionReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetTransactionReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/GetTransactionReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetTransactionReceipt(ctx, req.(*GetTransactionByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_StatisticsNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).StatisticsNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/StatisticsNodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).StatisticsNodeInfo(ctx, req.(*NodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_NewAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).NewAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/NewAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).NewAccount(ctx, req.(*NewAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_UnlockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).UnlockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/UnlockAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).UnlockAccount(ctx, req.(*UnlockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_LockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).LockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/LockAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).LockAccount(ctx, req.(*LockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_SignTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).SignTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/SignTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).SignTransaction(ctx, req.(*SignTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_SendTransactionWithPassphrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionPassphraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).SendTransactionWithPassphrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/SendTransactionWithPassphrase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).SendTransactionWithPassphrase(ctx, req.(*SendTransactionPassphraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetDynasty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDynastyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetDynasty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.APIService/GetDynasty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetDynasty(ctx, req.(*GetDynastyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNebState",
			Handler:    _APIService_GetNebState_Handler,
		},
		{
			MethodName: "NodeInfo",
			Handler:    _APIService_NodeInfo_Handler,
		},
		{
			MethodName: "BlockDump",
			Handler:    _APIService_BlockDump_Handler,
		},
		{
			MethodName: "Accounts",
			Handler:    _APIService_Accounts_Handler,
		},
		{
			MethodName: "GetAccountState",
			Handler:    _APIService_GetAccountState_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _APIService_SendTransaction_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _APIService_Call_Handler,
		},
		{
			MethodName: "SendRawTransaction",
			Handler:    _APIService_SendRawTransaction_Handler,
		},
		{
			MethodName: "GetBlockByHash",
			Handler:    _APIService_GetBlockByHash_Handler,
		},
		{
			MethodName: "GetTransactionReceipt",
			Handler:    _APIService_GetTransactionReceipt_Handler,
		},
		{
			MethodName: "StatisticsNodeInfo",
			Handler:    _APIService_StatisticsNodeInfo_Handler,
		},
		{
			MethodName: "NewAccount",
			Handler:    _APIService_NewAccount_Handler,
		},
		{
			MethodName: "UnlockAccount",
			Handler:    _APIService_UnlockAccount_Handler,
		},
		{
			MethodName: "LockAccount",
			Handler:    _APIService_LockAccount_Handler,
		},
		{
			MethodName: "SignTransaction",
			Handler:    _APIService_SignTransaction_Handler,
		},
		{
			MethodName: "SendTransactionWithPassphrase",
			Handler:    _APIService_SendTransactionWithPassphrase_Handler,
		},
		{
			MethodName: "GetDynasty",
			Handler:    _APIService_GetDynasty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_rpc.proto",
}

func init() { proto.RegisterFile("api_rpc.proto", fileDescriptorApiRpc) }

var fileDescriptorApiRpc = []byte{
	// 1595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0x4b, 0x6f, 0xdc, 0x36,
	0x10, 0x86, 0xd6, 0xaf, 0xd5, 0x38, 0x7e, 0xd1, 0x2f, 0x59, 0x7e, 0x64, 0xc3, 0xa0, 0xc8, 0x26,
	0x45, 0xbc, 0x4d, 0x52, 0x34, 0x40, 0x6f, 0x79, 0x14, 0x8e, 0x81, 0x34, 0x30, 0xe4, 0x34, 0xbd,
	0xa4, 0x58, 0x70, 0x25, 0x66, 0x97, 0x88, 0x56, 0x54, 0x44, 0xae, 0x1d, 0xfb, 0xd0, 0x43, 0x6f,
	0x3d, 0xf7, 0x1f, 0xf4, 0xd6, 0x5f, 0xd2, 0x43, 0x81, 0x5e, 0xfa, 0x0b, 0x0a, 0xf4, 0xd6, 0x3f,
	0xd0, 0x63, 0x41, 0x8a, 0x7a, 0xec, 0x4a, 0x1b, 0x23, 0xc7, 0xf6, 0xc6, 0x19, 0x0e, 0x67, 0x3e,
	0xce, 0x8b, 0x43, 0x58, 0x22, 0x31, 0xeb, 0x26, 0xb1, 0x7f, 0x18, 0x27, 0x5c, 0x72, 0x34, 0x97,
	0xc4, 0x7e, 0xdc, 0x73, 0xf7, 0xfa, 0x9c, 0xf7, 0x43, 0xda, 0x21, 0x31, 0xeb, 0x90, 0x28, 0xe2,
	0x92, 0x48, 0xc6, 0x23, 0x91, 0x0a, 0xb9, 0x0f, 0xfa, 0x4c, 0x0e, 0x46, 0xbd, 0x43, 0x9f, 0x0f,
	0x3b, 0x11, 0xed, 0x8d, 0x42, 0x22, 0x18, 0xef, 0xf4, 0xf9, 0x5d, 0x43, 0x74, 0x7c, 0x9e, 0xd0,
	0x4e, 0xdc, 0xeb, 0xf4, 0x42, 0xee, 0xbf, 0x4d, 0x0f, 0xe1, 0x0d, 0x40, 0x47, 0x54, 0xbe, 0xa0,
	0xbd, 0x53, 0x49, 0x24, 0xf5, 0xe8, 0xbb, 0x11, 0x15, 0x12, 0xaf, 0xc1, 0xca, 0x0b, 0x1e, 0xd0,
	0xe3, 0xe8, 0x0d, 0xcf, 0x58, 0xbf, 0xcc, 0xc0, 0x6a, 0xc1, 0x13, 0x31, 0x8f, 0x04, 0x45, 0xcb,
	0xd0, 0x60, 0x81, 0x63, 0xb5, 0xac, 0xb6, 0xed, 0x35, 0x58, 0x80, 0x76, 0xa0, 0xe9, 0x0f, 0x08,
	0x8b, 0xba, 0x2c, 0x70, 0x1a, 0x2d, 0xab, 0xbd, 0xe4, 0x2d, 0x68, 0xfa, 0x38, 0x40, 0x0e, 0x2c,
	0x9c, 0xd1, 0x44, 0x30, 0x1e, 0x39, 0x33, 0xe9, 0x8e, 0x21, 0xd1, 0x3e, 0x40, 0x4c, 0x69, 0xd2,
	0xf5, 0xf9, 0x28, 0x92, 0xce, 0xac, 0xde, 0xb4, 0x15, 0xe7, 0x89, 0x62, 0x20, 0x0c, 0xd7, 0xc4,
	0x45, 0xe4, 0x0f, 0x12, 0x1e, 0xb1, 0x4b, 0x1a, 0x38, 0x73, 0x2d, 0xab, 0xdd, 0xf4, 0xc6, 0x78,
	0xe8, 0x3a, 0x2c, 0xf6, 0x46, 0xfe, 0x5b, 0x2a, 0xbb, 0x82, 0x5d, 0x52, 0x67, 0xbe, 0x65, 0xb5,
	0xe7, 0x3c, 0x48, 0x59, 0xa7, 0xec, 0x92, 0xa2, 0x36, 0xac, 0x26, 0x34, 0x24, 0x17, 0x5d, 0x9f,
	0xf8, 0x03, 0x9a, 0x4a, 0x2d, 0x68, 0xa9, 0x65, 0xcd, 0x7f, 0xa2, 0xd8, 0x5a, 0xf2, 0x0e, 0xac,
	0x09, 0x99, 0x50, 0x32, 0xec, 0x0a, 0xc9, 0x13, 0x23, 0xda, 0xd4, 0xa2, 0x2b, 0xe9, 0xc6, 0xa9,
	0xe2, 0x6b, 0xd9, 0x87, 0xe0, 0x8c, 0xc9, 0xd2, 0xf7, 0x92, 0x46, 0x41, 0x7a, 0xc4, 0xd6, 0x47,
	0x36, 0x4b, 0x47, 0xbe, 0xd2, 0xbb, 0xfa, 0xe0, 0x6d, 0x58, 0xd5, 0xee, 0xf7, 0x79, 0xd8, 0xcd,
	0xbc, 0x02, 0xda, 0x8b, 0x2b, 0x19, 0xff, 0x95, 0xf1, 0xce, 0x7d, 0x58, 0x4c, 0xf8, 0x48, 0xd2,
	0xae, 0x24, 0xbd, 0x90, 0x3a, 0x8b, 0xad, 0x99, 0xf6, 0xe2, 0xfd, 0xb5, 0x43, 0x9d, 0x10, 0x87,
	0x9e, 0xda, 0x79, 0xa9, 0x36, 0x3c, 0x48, 0xf2, 0x35, 0xfe, 0x1e, 0x5c, 0x15, 0x4e, 0x26, 0x24,
	0xf3, 0x45, 0x25, 0x68, 0x5b, 0x30, 0xaf, 0x79, 0x4f, 0x4d, 0xe0, 0x0c, 0xa5, 0xf8, 0xcf, 0x28,
	0xeb, 0x0f, 0xa4, 0x0e, 0xdd, 0xac, 0x67, 0x28, 0x84, 0x60, 0xf6, 0x19, 0x11, 0x03, 0x1d, 0x36,
	0xdb, 0xd3, 0x6b, 0xb4, 0x07, 0xf6, 0x49, 0x16, 0xa1, 0x2c, 0x64, 0x39, 0x03, 0x7f, 0x01, 0x50,
	0x20, 0xab, 0x24, 0x89, 0x03, 0x0b, 0x24, 0x08, 0x12, 0x2a, 0x84, 0xd3, 0x68, 0xcd, 0xb4, 0x6d,
	0x2f, 0x23, 0xf1, 0xdf, 0x16, 0xac, 0x8f, 0x65, 0xa3, 0x41, 0x5c, 0x4e, 0x2b, 0x6b, 0x3c, 0xad,
	0x10, 0xcc, 0x4a, 0xc2, 0x42, 0x0d, 0xd9, 0xf6, 0xf4, 0x1a, 0xb9, 0xd0, 0xf4, 0x39, 0x8b, 0x7a,
	0x44, 0x50, 0x03, 0x3a, 0xa7, 0xaf, 0x4a, 0xb6, 0x5d, 0xb0, 0x99, 0xe8, 0x0e, 0x59, 0xc4, 0xa2,
	0xbe, 0xc9, 0xb4, 0x26, 0x13, 0x5f, 0x6b, 0xba, 0x36, 0x6a, 0xf3, 0xf5, 0x51, 0x9b, 0x4c, 0xda,
	0x85, 0x6a, 0xd2, 0xaa, 0x22, 0x7b, 0xe4, 0x6b, 0x1c, 0x22, 0x2b, 0xb2, 0xcf, 0x60, 0xb5, 0x60,
	0x99, 0xcb, 0xef, 0x81, 0x6d, 0xfc, 0x43, 0x85, 0x63, 0x69, 0x87, 0x15, 0x0c, 0xfc, 0x0c, 0xb6,
	0x8e, 0xa8, 0x34, 0x87, 0xca, 0x35, 0x5c, 0x76, 0x73, 0xea, 0xfb, 0x8c, 0x44, 0x1b, 0x30, 0xa7,
	0x5b, 0x80, 0x71, 0x5a, 0x4a, 0xe0, 0x63, 0xd8, 0xae, 0x68, 0x32, 0x10, 0x1c, 0x58, 0xe8, 0x91,
	0x90, 0x44, 0x3e, 0xcd, 0x54, 0x19, 0x52, 0xa9, 0x8a, 0xb8, 0xe2, 0x1b, 0x55, 0x9a, 0xc0, 0xeb,
	0xb0, 0x76, 0x44, 0xe5, 0xd3, 0x8b, 0x88, 0x08, 0x79, 0x91, 0xdd, 0xed, 0x73, 0xdd, 0x69, 0x72,
	0xa6, 0x51, 0x7d, 0x00, 0x10, 0xd0, 0x90, 0xf6, 0x89, 0xa4, 0xf9, 0xf5, 0x4a, 0x1c, 0xfc, 0xbb,
	0x05, 0x5b, 0xa7, 0x34, 0x0a, 0x5e, 0x26, 0x24, 0x12, 0xc4, 0x57, 0xfd, 0x2e, 0xbb, 0x20, 0x82,
	0xd9, 0x37, 0x09, 0x1f, 0x1a, 0x48, 0x7a, 0xad, 0x72, 0x4d, 0x72, 0x03, 0xa6, 0x21, 0xb9, 0xc2,
	0x77, 0x46, 0xc2, 0x51, 0x96, 0x07, 0x29, 0x51, 0xa0, 0x9e, 0xd5, 0x89, 0x9e, 0x12, 0x2a, 0xff,
	0x05, 0x1f, 0x25, 0x3e, 0xd5, 0x81, 0xb7, 0x3d, 0x43, 0x29, 0x3b, 0x24, 0xe9, 0x0b, 0x13, 0x6a,
	0xbd, 0x56, 0x79, 0xd2, 0x27, 0xa2, 0x1b, 0x27, 0xcc, 0x4f, 0x1b, 0x89, 0xed, 0x35, 0xfb, 0x44,
	0x9c, 0x28, 0x3a, 0xdb, 0x0c, 0xd9, 0x90, 0x49, 0xdd, 0x3a, 0xd2, 0xcd, 0xe7, 0x8a, 0xc6, 0xbf,
	0x5a, 0xb0, 0xf8, 0x84, 0x84, 0xe1, 0x47, 0xde, 0x22, 0xc5, 0x3b, 0x53, 0xc6, 0xeb, 0x42, 0xf3,
	0xcd, 0x28, 0xd2, 0x2e, 0xd1, 0x17, 0xb1, 0xbd, 0x9c, 0xce, 0x31, 0xcf, 0x4d, 0xc3, 0x3c, 0xff,
	0x21, 0xcc, 0x0b, 0xe3, 0x98, 0x0b, 0x2f, 0x36, 0x4b, 0x5e, 0xc4, 0x1d, 0xd8, 0x51, 0x91, 0xf1,
	0xc8, 0x79, 0x7d, 0x70, 0x02, 0x22, 0x89, 0xbe, 0xd6, 0x35, 0x4f, 0xaf, 0xf1, 0x6b, 0xd8, 0xae,
	0x84, 0xb2, 0xe8, 0x49, 0xf2, 0xfd, 0x40, 0x75, 0x19, 0xd3, 0x93, 0x52, 0x4a, 0x95, 0x9c, 0xcf,
	0x23, 0x99, 0x10, 0x5f, 0x76, 0x8b, 0xa6, 0xa1, 0x4b, 0x2e, 0xe3, 0x3f, 0x32, 0xcd, 0xe3, 0x53,
	0xd8, 0x3c, 0xa2, 0xf2, 0xb1, 0xca, 0xe5, 0xc7, 0x17, 0xaa, 0x49, 0x95, 0xa0, 0x94, 0x34, 0xeb,
	0x35, 0xbe, 0x07, 0xbb, 0x47, 0x54, 0x96, 0x90, 0x5c, 0x7d, 0xa4, 0x0d, 0xab, 0x5a, 0xf9, 0xd3,
	0xd1, 0x30, 0xce, 0xe4, 0x36, 0x60, 0x2e, 0x6d, 0x24, 0x96, 0xee, 0xf6, 0x29, 0x81, 0x6f, 0xc1,
	0x5a, 0x49, 0xd2, 0xdc, 0xb0, 0xec, 0x10, 0xdb, 0x38, 0xe4, 0x4f, 0x0b, 0xdc, 0x31, 0x6f, 0xf8,
	0x94, 0xc5, 0xb2, 0x7c, 0x64, 0x12, 0x45, 0x9e, 0x2e, 0x8d, 0x4a, 0xba, 0xcc, 0x54, 0xd3, 0x65,
	0x2c, 0xbd, 0xf7, 0xc0, 0x96, 0x6c, 0x48, 0x85, 0x24, 0xc3, 0x58, 0xe7, 0xc5, 0x8c, 0x57, 0x30,
	0x72, 0x78, 0xf3, 0x05, 0x3c, 0x55, 0xf6, 0xa6, 0xcd, 0xea, 0x8c, 0x28, 0x75, 0xdd, 0xba, 0xb0,
	0x34, 0xeb, 0xc3, 0xf2, 0x00, 0xd6, 0x5e, 0xd0, 0x73, 0xd3, 0x56, 0x32, 0xbf, 0x1d, 0x00, 0xc4,
	0x44, 0x88, 0x78, 0x90, 0xa8, 0x1e, 0x9d, 0xde, 0xaf, 0xc4, 0xc1, 0x87, 0x80, 0xca, 0x87, 0x8a,
	0x36, 0x54, 0xdf, 0xd1, 0xf0, 0x09, 0x6c, 0x7c, 0x13, 0x29, 0x97, 0x4f, 0xd8, 0x99, 0xde, 0x03,
	0xc7, 0x11, 0x34, 0x2a, 0x08, 0x3a, 0xb0, 0x39, 0xa1, 0xb1, 0xc8, 0xd4, 0x84, 0x8a, 0x51, 0x98,
	0xc6, 0xbc, 0xe9, 0x19, 0x4a, 0x41, 0x7e, 0xfe, 0x11, 0x00, 0xf0, 0x5d, 0x58, 0x7f, 0xfe, 0x11,
	0xea, 0x75, 0x1f, 0x64, 0xfd, 0xe8, 0x7f, 0xd3, 0x07, 0xef, 0xc2, 0x76, 0xe5, 0x3e, 0x35, 0xa5,
	0x92, 0xf5, 0x8e, 0x7f, 0x2c, 0x68, 0x4d, 0x34, 0x8f, 0x93, 0x3c, 0x5a, 0xff, 0x69, 0x4f, 0x4c,
	0xa4, 0xa2, 0x5d, 0x49, 0xc5, 0x87, 0x70, 0xe3, 0x03, 0x37, 0x9f, 0xde, 0x2b, 0xee, 0xff, 0xb6,
	0x0c, 0xf0, 0xe8, 0xe4, 0xf8, 0x94, 0x26, 0x67, 0x0a, 0x44, 0x17, 0x16, 0x4b, 0xc3, 0x15, 0xda,
	0x31, 0x33, 0x64, 0x75, 0xfc, 0x77, 0xdd, 0xba, 0xad, 0xd4, 0x10, 0xde, 0xf9, 0xe1, 0x8f, 0xbf,
	0x7e, 0x6a, 0xac, 0xa3, 0xb5, 0xce, 0xd9, 0xbd, 0xce, 0x48, 0xd0, 0x44, 0xfd, 0x35, 0x84, 0xd6,
	0xf8, 0x0a, 0x9a, 0xd9, 0xb0, 0x89, 0xb6, 0x8c, 0x8a, 0x89, 0x6f, 0x84, 0xbb, 0x5d, 0xe1, 0x4f,
	0xd7, 0xcb, 0x03, 0xca, 0x94, 0xae, 0xef, 0xc0, 0xce, 0xfb, 0x29, 0xca, 0x14, 0x4c, 0xf6, 0x62,
	0xd7, 0xa9, 0x6e, 0x18, 0xd5, 0xfb, 0x5a, 0xf5, 0x36, 0x46, 0xb9, 0x6a, 0x3d, 0xf1, 0x04, 0xa3,
	0x61, 0xfc, 0xa5, 0x75, 0x47, 0xc1, 0xce, 0x86, 0xae, 0x1c, 0xf6, 0xc4, 0x60, 0x96, 0xc3, 0x9e,
	0x9c, 0xce, 0x6a, 0x60, 0x93, 0x4c, 0x57, 0x02, 0x2b, 0x13, 0x03, 0x15, 0xda, 0x2f, 0x1c, 0x5b,
	0x33, 0xb2, 0xb9, 0x07, 0xd3, 0xb6, 0x8d, 0xb1, 0x96, 0x36, 0xe6, 0xe2, 0xcd, 0x8a, 0x31, 0x25,
	0xa6, 0xee, 0xf2, 0x0e, 0x56, 0x26, 0x72, 0x25, 0xb7, 0x59, 0x3f, 0x45, 0xe5, 0x36, 0xa7, 0xbc,
	0xcc, 0xf8, 0xba, 0xb6, 0xb9, 0x83, 0x37, 0x72, 0x9b, 0xb2, 0x90, 0x52, 0x26, 0x5f, 0xc2, 0xac,
	0x9a, 0x67, 0x10, 0x32, 0x8a, 0x4a, 0xc3, 0xcd, 0x95, 0xca, 0x1d, 0xad, 0x1c, 0xe1, 0xa5, 0x5c,
	0xb9, 0x4f, 0xc2, 0x50, 0x69, 0xbd, 0x04, 0x54, 0x1d, 0x2e, 0x50, 0xab, 0xa4, 0xaf, 0x76, 0xee,
	0xb8, 0xd2, 0x22, 0xd6, 0x16, 0xf7, 0xf0, 0x76, 0x6e, 0x31, 0x21, 0xe7, 0x13, 0x37, 0x22, 0xb0,
	0x3c, 0x3e, 0x49, 0xa0, 0xbd, 0x22, 0x30, 0xd5, 0x01, 0xc3, 0x5d, 0x3a, 0x54, 0x3f, 0xeb, 0x2c,
	0xf5, 0x6a, 0x4c, 0xf4, 0xc7, 0x8e, 0x29, 0x13, 0x3f, 0x5a, 0x7a, 0x5a, 0xa9, 0x3e, 0xfe, 0x08,
	0x17, 0xa6, 0xa6, 0x8d, 0x27, 0xee, 0x0d, 0x23, 0x33, 0x7d, 0x76, 0xc0, 0xb7, 0x35, 0x88, 0x9b,
	0xf8, 0xa0, 0x0c, 0xa2, 0x2a, 0xaf, 0xb0, 0x9c, 0x01, 0xaa, 0xfe, 0x16, 0xa7, 0x16, 0x70, 0x66,
	0x7b, 0xfa, 0x07, 0x13, 0x7f, 0xa2, 0x6d, 0x5f, 0x47, 0xfb, 0xca, 0x36, 0x09, 0x86, 0x2c, 0xea,
	0x88, 0x5c, 0x5a, 0x97, 0xb5, 0xb6, 0xe0, 0x03, 0x14, 0x8f, 0x3c, 0xca, 0xca, 0xb7, 0x32, 0x2c,
	0xb8, 0x3b, 0x35, 0x3b, 0x75, 0x05, 0x91, 0x5a, 0x32, 0x15, 0xd1, 0x89, 0xe8, 0xb9, 0xba, 0x1c,
	0x87, 0xa5, 0xb1, 0x77, 0x1c, 0xed, 0x1a, 0x6d, 0x75, 0xf3, 0x82, 0xbb, 0x57, 0xbf, 0x69, 0xac,
	0xdd, 0xd4, 0xd6, 0xf6, 0xb1, 0x53, 0xb5, 0x36, 0xd2, 0x07, 0x94, 0xc1, 0x3e, 0x2c, 0x96, 0xde,
	0xf5, 0xbc, 0xcb, 0x56, 0x67, 0x83, 0xbc, 0xcb, 0xd6, 0x8c, 0x01, 0xf8, 0x86, 0x36, 0xb5, 0x8b,
	0xb7, 0xaa, 0xa6, 0x32, 0x43, 0x6f, 0x61, 0x65, 0xe2, 0x01, 0x2d, 0x4a, 0xbd, 0x76, 0x50, 0x28,
	0x6a, 0xa3, 0xfe, 0xdd, 0xcd, 0x7a, 0x19, 0x5e, 0x2e, 0xc5, 0x8d, 0xf5, 0x75, 0x49, 0xfc, 0x6c,
	0xc1, 0xfe, 0x44, 0x49, 0x7d, 0xcb, 0xe4, 0xa0, 0x78, 0x88, 0xd0, 0xad, 0xfa, 0xc2, 0xab, 0x3c,
	0xd2, 0x6e, 0xfb, 0x6a, 0x41, 0x83, 0xe7, 0x50, 0xe3, 0x69, 0xe3, 0x9b, 0x05, 0x1e, 0x39, 0xcd,
	0xbe, 0x02, 0xf9, 0x1a, 0xa0, 0xf8, 0x61, 0xe6, 0x09, 0x55, 0xf9, 0x89, 0xba, 0x3b, 0x35, 0x3b,
	0x75, 0xed, 0x3c, 0x35, 0x19, 0xa4, 0x22, 0xbd, 0x79, 0xfd, 0xc7, 0x7f, 0xf0, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0x1c, 0x97, 0xea, 0x9b, 0x13, 0x00, 0x00,
}
